# Generated by Django 5.2.17 on 2026-08-25 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_registration_enabled', models.BooleanField(default=True)),
                ('google_login_enabled', models.BooleanField(default=True)),
                ('microsoft_login_enabled', models.BooleanField(default=True)),
                ('default_external_role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_manager', 'Project Manager'), ('support_agent', 'Support Agent'), ('requester', 'Requester/User'), ('viewer', 'Viewer/Auditor'), ('guest', 'Guest')], default='guest', max_length=30)),
                ('allowed_email_domains', models.JSONField(blank=True, default=list)),
                ('external_users_require_approval', models.BooleanField(default=False)),
                ('guest_ticket_visibility', models.CharField(choices=[('own', 'Own only'), ('own_group', 'Own and allowed group')], default='own', max_length=20)),
                ('default_external_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Account policies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_manager', 'Project Manager'), ('support_agent', 'Support Agent'), ('requester', 'Requester/User'), ('viewer', 'Viewer/Auditor'), ('guest', 'Guest')], db_index=True, default='guest', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=5)),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('is_external', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('guest_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
