# Generated by Django 5.2.17 on 2026-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_preferences_and_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_mode',
            field=models.CharField(choices=[('full', 'Full navigation'), ('mini', 'Icon-only navigation'), ('hidden', 'Hidden navigation')], default='mini', max_length=10),
        ),
    ]
