# Generated by Django 6.1.1 on 2026-10-01 09:51

import django.db.models.deletion
from django.db import migrations, models


def copy_organizations(apps, schema_editor):
    from django.core.management.color import no_style
    alias = schema_editor.connection.alias
    Type, Organization, Legacy = [apps.get_model(app, model) for app, model in [('accounts','OrganizationType'),('accounts','Organization'),('tpa','TPAOrganization')]]
    names = [('INSURER','Insurance Company'),('INDIVIDUAL','Individual'),('CORPORATE','Corporate'),('BROKER','Broker'),('AGENT','Agent'),('BRANCH','Branch'),('TPA','Third Party Administrator'),('SERVICE_PROVIDER','Service Provider'),('HEALTHCARE','Healthcare Provider'),('REINSURER','Reinsurer'),('SURVEYOR','Surveyor / Loss Adjuster'),('LAW_FIRM','Law Firm'),('VENDOR','Vendor'),('DEPARTMENT','Internal Department'),('OTHER','Other')]
    for index, (code,name) in enumerate(names):
        Type.objects.using(alias).get_or_create(code=code,defaults={'name':name,'display_order':index})
    fields = ['code','name_en','name_ar','commercial_registration','contact_name','contact_email','contact_phone','is_active']
    for old in Legacy.objects.using(alias).all().iterator():
        Type.objects.using(alias).get_or_create(code=old.organization_type,defaults={'name':old.organization_type})
        new=Organization.objects.using(alias).create(pk=old.pk,organization_type_id=old.organization_type,**{key:getattr(old,key) for key in fields})
        Organization.objects.using(alias).filter(pk=new.pk).update(created_at=old.created_at,updated_at=old.updated_at)
    if Organization.objects.using(alias).count() != Legacy.objects.using(alias).count():
        raise RuntimeError('Organization copy count mismatch.')
    CT, Permission, Group, User = [apps.get_model(app,model) for app,model in [('contenttypes','ContentType'),('auth','Permission'),('auth','Group'),('auth','User')]]
    ct,_ = CT.objects.using(alias).get_or_create(app_label='accounts',model='organization')
    for old in Permission.objects.using(alias).filter(content_type__app_label='tpa',content_type__model='tpaorganization'):
        action = old.codename.split('_',1)[0]
        new,_=Permission.objects.using(alias).get_or_create(content_type=ct,codename=f'{action}_organization',defaults={'name':f'Can {action} organization'})
        for group in Group.objects.using(alias).filter(permissions=old):group.permissions.add(new)
        for user in User.objects.using(alias).filter(user_permissions=old):user.user_permissions.add(new)
    for sql in schema_editor.connection.ops.sequence_reset_sql(no_style(),[Organization]):schema_editor.execute(sql)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_organizations'),
        ('tpa', '0014_merge_20260930_1202'),
        ('tickets', '0008_supportgroup_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=180)),
                ('name_ar', models.CharField(blank=True, max_length=180)),
                ('commercial_registration', models.CharField(blank=True, max_length=80)),
                ('tax_number', models.CharField(blank=True, max_length=80)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.organization')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='accounts.organizationtype', to_field='code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(copy_organizations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Organizations this user may act for across portal workflows.', related_name='user_profiles', to='accounts.organization'),
        ),
    ]
