# Generated by Django 6.1.1 on 2026-10-02 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizationtype_remove_userprofile_organizations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Block sign-in and email notifications for this account.'),
        ),
        migrations.CreateModel(
            name='PasswordResetChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('link', 'Email link'), ('otp', 'Email OTP')], max_length=10)),
                ('email_digest', models.CharField(db_index=True, max_length=64)),
                ('ip_digest', models.CharField(db_index=True, max_length=64)),
                ('session_digest', models.CharField(max_length=64)),
                ('password_stamp', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
