from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0003_tpa_document_intelligence"),
        ("tickets", "0007_category_allowed_groups"),
        ("tpa", "0006_transaction_query_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Temporarily Suspended"),
                    ("terminated", "Terminated"),
                    ("voided", "Deleted / Voided"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="memberpolicyenrollment",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Temporarily Suspended"),
                    ("terminated", "Terminated"),
                    ("voided", "Voided"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(model_name="memberpolicyenrollment", name="suspension_date", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="memberpolicyenrollment", name="suspension_reason", field=models.TextField(blank=True)),
        migrations.AddField(model_name="memberpolicyenrollment", name="expected_reactivation_date", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="memberpolicyenrollment", name="reactivation_date", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="policy", name="physical_card_required", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="membertransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("NEW_POLICY_ENROLLMENT", "New Policy Enrollment"),
                    ("MEMBER_ADD", "Member Addition"),
                    ("MEMBER_TERMINATE", "Member Termination"),
                    ("MEMBER_SUSPEND", "Temporary Suspension"),
                    ("MEMBER_REACTIVATE", "Member Reactivation"),
                    ("MEMBER_DELETE", "Member Deletion / Void"),
                    ("POLICY_CANCEL", "Policy Cancellation"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="membertransaction",
            name="refund_basis",
            field=models.CharField(
                choices=[("NONE", "Not Applicable"), ("FULL", "Full Refund"), ("PRO_RATA", "Pro-Rata Refund")],
                db_index=True,
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(model_name="membertransaction", name="classification", field=models.CharField(blank=True, db_index=True, max_length=40)),
        migrations.AddField(model_name="membertransaction", name="classification_confidence", field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
        migrations.AddField(model_name="membertransaction", name="validation_completed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="membertransaction", name="physical_card_required", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="memberaction", name="provenance", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(
            model_name="transactionquery",
            name="purpose",
            field=models.CharField(
                choices=[("APPROVAL", "Approval Query"), ("TPA", "TPA Query"), ("CLIENT", "Client Query")],
                db_index=True,
                default="TPA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transactionquery",
            name="audience",
            field=models.CharField(
                choices=[
                    ("CLIENT_VISIBLE", "Client Visible"),
                    ("INSURER_TPA_INTERNAL", "Insurer / TPA Internal"),
                    ("SELECTED_PARTICIPANTS", "Selected Participants"),
                ],
                db_index=True,
                default="CLIENT_VISIBLE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="transactionquery",
            name="selected_participants",
            field=models.ManyToManyField(blank=True, related_name="selected_tpa_queries", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="transactionquerymessage",
            name="audience",
            field=models.CharField(
                choices=[
                    ("CLIENT_VISIBLE", "Client Visible"),
                    ("INSURER_TPA_INTERNAL", "Insurer / TPA Internal"),
                    ("SELECTED_PARTICIPANTS", "Selected Participants"),
                ],
                db_index=True,
                default="CLIENT_VISIBLE",
                max_length=30,
            ),
        ),
        migrations.AddField(model_name="transactionquerymessage", name="shared_with_client_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(
            model_name="transactionquerymessage",
            name="shared_with_client_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_tpa_query_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inboundemail",
            name="processing_state",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Received"),
                    ("PROCESSING", "Processing"),
                    ("REVIEW", "Needs review"),
                    ("PROCESSED", "Processed"),
                    ("FAILED", "Failed"),
                    ("IGNORED", "Not Endorsement / Ignored"),
                    ("UNAUTHORIZED", "Unauthorized Sender"),
                ],
                db_index=True,
                default="RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AddField(model_name="inboundemail", name="graph_message_id", field=models.CharField(blank=True, db_index=True, max_length=255)),
        migrations.AddField(model_name="inboundemail", name="internet_message_id", field=models.CharField(blank=True, db_index=True, max_length=500)),
        migrations.AddField(model_name="inboundemail", name="conversation_id", field=models.CharField(blank=True, db_index=True, max_length=255)),
        migrations.AddField(model_name="inboundemail", name="mailbox", field=models.EmailField(blank=True, db_index=True, max_length=254)),
        migrations.AddField(model_name="inboundemail", name="sender_name", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="inboundemail", name="to_addresses", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="inboundemail", name="cc_addresses", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="inboundemail", name="body_html", field=models.TextField(blank=True)),
        migrations.AddField(model_name="inboundemail", name="source_hash", field=models.CharField(blank=True, db_index=True, max_length=64)),
        migrations.AddField(model_name="inboundemail", name="raw_ai_output", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="inboundemail", name="classification", field=models.CharField(blank=True, db_index=True, max_length=40)),
        migrations.AddField(model_name="inboundemail", name="classification_confidence", field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
        migrations.AddField(model_name="inboundemail", name="processing_stage", field=models.CharField(blank=True, max_length=50)),
        migrations.CreateModel(
            name="TPAMailboxSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="office365_graph", max_length=40)),
                ("mailbox", models.EmailField(max_length=254)),
                ("folder", models.CharField(default="Inbox", max_length=120)),
                ("delta_link", models.TextField(blank=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("messages_processed", models.PositiveIntegerField(default=0)),
                ("messages_review", models.PositiveIntegerField(default=0)),
                ("messages_ignored", models.PositiveIntegerField(default=0)),
                ("messages_failed", models.PositiveIntegerField(default=0)),
                ("scheduler_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="tpamailboxsyncstate",
            constraint=models.UniqueConstraint(fields=("provider", "mailbox", "folder"), name="tpa_unique_mailbox_sync_state"),
        ),
        migrations.CreateModel(
            name="TPAEmailAuthority",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_address", models.EmailField(db_index=True, max_length=254)),
                ("permitted_transaction_types", models.JSONField(blank=True, default=list)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email_authorities", to="tpa.tpaorganization")),
                ("policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="email_authorities", to="tpa.policy")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tpa_email_authorities", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="tpaemailauthority",
            constraint=models.UniqueConstraint(fields=("email_address", "organization", "policy"), name="tpa_unique_email_authority"),
        ),
        migrations.AddIndex(
            model_name="tpaemailauthority",
            index=models.Index(fields=["email_address", "active"], name="tpa_email_a_email_a_4fd468_idx"),
        ),
        migrations.CreateModel(
            name="ExtractionAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.CharField(max_length=50)),
                ("status", models.CharField(choices=[("STARTED", "Started"), ("SUCCESS", "Success"), ("REVIEW", "Needs Review"), ("FAILED", "Failed")], db_index=True, default="STARTED", max_length=20)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("error", models.TextField(blank=True)),
                ("raw_output", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("inbound_attachment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="extraction_attempts", to="tpa.inboundemailattachment")),
                ("provider", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tpa_extraction_attempts", to="ai.aiproviderconfig")),
                ("source_document", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="extraction_attempts", to="tpa.sourcedocument")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CardDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(blank=True, choices=[("COURIER", "Courier"), ("HAND_DELIVERY", "Hand Delivery"), ("CLIENT_COLLECTION", "Collected by Client"), ("INSURER_COLLECTION", "Collected by Insurance Company"), ("TPA_COLLECTION", "Collected from TPA"), ("OTHER", "Other")], max_length=30)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("READY", "Ready for Dispatch"), ("DISPATCHED", "Dispatched"), ("IN_TRANSIT", "In Transit"), ("READY_COLLECTION", "Ready for Collection"), ("COLLECTED", "Collected"), ("DELIVERED", "Delivered"), ("FAILED", "Failed / Returned"), ("NOT_REQUIRED", "Not Required")], db_index=True, default="PENDING", max_length=30)),
                ("courier_company", models.CharField(blank=True, max_length=160)),
                ("tracking_number", models.CharField(blank=True, db_index=True, max_length=120)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("expected_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_or_collected_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_name", models.CharField(blank=True, max_length=160)),
                ("recipient_organization", models.CharField(blank=True, max_length=180)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                ("proof_attachment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tpa_card_dispatch_proofs", to="tickets.ticketattachment")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recorded_tpa_card_dispatches", to=settings.AUTH_USER_MODEL)),
                ("transaction", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="card_dispatch", to="tpa.membertransaction")),
            ],
        ),
    ]
