# Generated by Django 6.1.1 on 2026-09-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0009_merge_20260929_automated_endorsements'),
        ('tpa', '0011_membertransaction_expected_reactivation_date'),
    ]

    operations = [
    ]
