# Generated by Django 6.1.1 on 2026-09-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0012_merge_20260929_2109'),
        ('tpa', '0012_merge_workflow_branches'),
    ]

    operations = [
    ]
