# Generated by Django 6.1.1 on 2026-09-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0013_member_demographic_change'),
        ('tpa', '0013_merge_20260930_0902'),
    ]

    operations = [
    ]
