# Generated by Django 6.1.1 on 2026-10-01 09:51

import django.db.models.deletion
from django.db import migrations, models


def restore_legacy_organizations(apps,schema_editor):
    from django.core.management.color import no_style
    Organization, Legacy = apps.get_model('accounts','Organization'), apps.get_model('tpa','TPAOrganization')
    alias = schema_editor.connection.alias
    fields=['code','name_en','name_ar','commercial_registration','contact_name','contact_email','contact_phone','is_active']
    for new in Organization.objects.using(alias).all().iterator():
        Legacy.objects.using(alias).update_or_create(pk=new.pk,defaults={'organization_type':new.organization_type_id,**{key:getattr(new,key) for key in fields}})
    for sql in schema_editor.connection.ops.sequence_reset_sql(no_style(),[Legacy]):schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizationtype_remove_userprofile_organizations_and_more'),
        ('core', '0013_alter_sitesettings_default_processing_organization'),
        ('tickets', '0009_ticketorganization_ticketsequence_tickettaggeduser_and_more'),
        ('tpa', '0014_merge_20260930_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='sponsor',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='sponsor',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='membertransaction',
            old_name='sponsor',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='tpaemailauthority',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_authorities', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insurance_company',
            field=models.ForeignKey(limit_choices_to={'organization_type': 'INSURER'}, on_delete=django.db.models.deletion.PROTECT, related_name='insured_policies', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurer_transactions', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='tpa_organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'organization_type': 'TPA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_policies', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='policyaccess',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_access', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='requester_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transactions', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='benefitplan',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefitplan',
            name='effective_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_emails', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(default='GROUP_MEDICAL', max_length=80),
        ),
        migrations.AddField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='tickets.product'),
        ),
        migrations.AddField(
            model_name='policy',
            name='workflow_organizations',
            field=models.ManyToManyField(blank=True, related_name='workflow_policies', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tpa_transaction', to='tickets.ticket'),
        ),
        migrations.AddConstraint(
            model_name='benefitplan',
            constraint=models.CheckConstraint(condition=models.Q(('annual_premium__gte', 0)), name='plan_nonnegative_premium'),
        ),
        migrations.AddConstraint(
            model_name='benefitplan',
            constraint=models.CheckConstraint(condition=models.Q(('default_sum_insured__isnull', True), ('default_sum_insured__gte', 0), _connector='OR'), name='plan_nonnegative_sum'),
        ),
        migrations.AddConstraint(
            model_name='benefitplan',
            constraint=models.CheckConstraint(condition=models.Q(('effective_from__isnull', True), ('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='plan_valid_dates'),
        ),
        migrations.RunPython(migrations.RunPython.noop, restore_legacy_organizations),
        migrations.DeleteModel(
            name='TPAOrganization',
        ),
    ]
