# Generated by Django 5.2.17 on 2026-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name_en', models.CharField(default='Greenline Insurance Services', max_length=150)),
                ('site_name_ar', models.CharField(default='جرين لاين لخدمات التأمين', max_length=150)),
                ('short_name', models.CharField(default='GLIS', max_length=30)),
                ('tagline_en', models.CharField(default='Insurance service, made clear', max_length=180)),
                ('tagline_ar', models.CharField(default='خدمات التأمين، بوضوح وسهولة', max_length=180)),
                ('contact_email', models.EmailField(default='care@glis.example', max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(default='+968 2400 0000', max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('address_en', models.CharField(default='Muscat, Sultanate of Oman', max_length=255)),
                ('address_ar', models.CharField(default='مسقط، سلطنة عُمان', max_length=255)),
                ('city', models.CharField(blank=True, default='Muscat', max_length=100)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Oman', max_length=100)),
                ('po_box', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('map_zoom', models.PositiveSmallIntegerField(default=15)),
                ('commercial_registration_no', models.CharField(blank=True, max_length=100)),
                ('vat_registration_no', models.CharField(blank=True, max_length=100)),
                ('license_no', models.CharField(blank=True, max_length=100)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('working_hours_en', models.CharField(blank=True, max_length=255)),
                ('working_hours_ar', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, upload_to='branding/')),
                ('public_registration_enabled', models.BooleanField(default=True)),
                ('public_theme_switcher_enabled', models.BooleanField(default=True)),
                ('organization_details', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
