# Generated by Django 5.2.17 on 2026-08-27 11:08

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_en', models.CharField(max_length=255)),
                ('question_ar', models.CharField(blank=True, max_length=255)),
                ('answer_en', models.TextField()),
                ('answer_ar', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_ar', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-check-circle', max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='cms/features/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow_en', models.CharField(default='Insurance service orchestration', max_length=120)),
                ('eyebrow_ar', models.CharField(default='تنسيق خدمات التأمين', max_length=120)),
                ('title_en', models.CharField(default='One clear path through every insurance request', max_length=220)),
                ('title_ar', models.CharField(default='مسار واضح لكل طلب تأميني', max_length=220)),
                ('subtitle_en', models.TextField(default='Submit, track and resolve service requests with secure collaboration across customers, providers and insurance teams.')),
                ('subtitle_ar', models.TextField(default='قدّم طلبات الخدمة وتابعها وأنجزها بتعاون آمن بين العملاء ومقدمي الخدمة وفرق التأمين.')),
                ('primary_cta_en', models.CharField(default='Submit a request', max_length=60)),
                ('primary_cta_ar', models.CharField(default='تقديم طلب', max_length=60)),
                ('primary_ctta_url', models.CharField(default='/portal/tickets/create/1/', max_length=255)),
                ('secondary_cta_en', models.CharField(default='Explore services', max_length=60)),
                ('secondary_cta_ar', models.CharField(default='استكشف الخدمات', max_length=60)),
                ('secondary_cta_url', models.CharField(default='#services', max_length=255)),
                ('hero_image', models.ImageField(blank=True, upload_to='cms/hero/')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.core.models.LocalizedModelMixin),
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('about', 'About'), ('services', 'Services'), ('why_us', 'Why Choose Us'), ('process', 'Process'), ('statistics', 'Statistics'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('faq', 'FAQ'), ('contact', 'Contact'), ('cta', 'Call To Action')], max_length=30, unique=True)),
                ('eyebrow_en', models.CharField(blank=True, max_length=120)),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('content_en', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cms/sections/')),
                ('button_text_en', models.CharField(blank=True, max_length=80)),
                ('button_text_ar', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(upload_to='cms/partners/')),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('title_en', models.CharField(max_length=160)),
                ('title_ar', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-check2-circle', max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(default='bi-grid', max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('label_en', models.CharField(max_length=120)),
                ('label_ar', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role_en', models.CharField(blank=True, max_length=120)),
                ('role_ar', models.CharField(blank=True, max_length=120)),
                ('quote_en', models.TextField()),
                ('quote_ar', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='cms/testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_ar', models.CharField(blank=True, max_length=160)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_ar', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-shield-check', max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='cms/services/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('button_text_en', models.CharField(blank=True, max_length=80)),
                ('button_text_ar', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory')),
            ],
            options={
                'ordering': ['order', 'title_en'],
            },
        ),
    ]
