# Generated by Django 5.2.17 on 2026-08-29 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_governorate_insurancepartner_managementmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='bi-folder', help_text='Bootstrap Icon class, e.g. bi-folder', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Download Category',
                'verbose_name_plural': 'Download Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='DownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Optional document/reference number', max_length=100)),
                ('file', models.FileField(upload_to='downloads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', 'jpg', 'jpeg', 'png', 'csv', 'txt'])])),
                ('version', models.CharField(blank=True, max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.downloadcategory')),
            ],
            options={
                'verbose_name': 'Download Document',
                'verbose_name_plural': 'Download Documents',
                'ordering': ['order', '-updated_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='core_downlo_categor_4ac036_idx'), models.Index(fields=['reference'], name='core_downlo_referen_4359ac_idx'), models.Index(fields=['is_featured'], name='core_downlo_is_feat_337d8d_idx')],
            },
        ),
    ]
