# Generated by Django 5.2.17 on 2026-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_downloadcategory_downloaddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Main Website Configuration', max_length=150)),
                ('show_management', models.BooleanField(default=True)),
                ('show_insurance_partners', models.BooleanField(default=True)),
                ('show_network_providers', models.BooleanField(default=True)),
                ('show_services', models.BooleanField(default=True)),
                ('show_statistics', models.BooleanField(default=True)),
                ('show_features', models.BooleanField(default=True)),
                ('show_process', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_faq', models.BooleanField(default=True)),
                ('show_download_center', models.BooleanField(default=True)),
                ('show_medical_contacts', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('download_categories', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.downloadcategory')),
                ('download_documents', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.downloaddocument')),
                ('faqs', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.faq')),
                ('features', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.feature')),
                ('home_sections', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.homesection')),
                ('insurance_partners', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.insurancepartner')),
                ('management_members', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.managementmember')),
                ('medical_contacts', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.medicalcontact')),
                ('medical_process_steps', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.medicalprocessstep')),
                ('network_providers', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.networkprovider')),
                ('partners', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.partner')),
                ('process_steps', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.processstep')),
                ('services', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.service')),
                ('statistics', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.statistic')),
                ('testimonials', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.testimonial')),
                ('tpa_services', models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.tpaservice')),
            ],
            options={
                'verbose_name': 'Frontend Configuration',
                'verbose_name_plural': 'Frontend Configuration',
            },
        ),
    ]
