# Generated by Django 5.2.17 on 2026-08-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_frontendconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendconfiguration',
            name='hero_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_configuration', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='frontendconfiguration',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='frontend_configurations', to='core.servicecategory'),
        ),
        migrations.AddField(
            model_name='frontendconfiguration',
            name='site_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_configuration', to='core.sitesettings'),
        ),
    ]
