# Generated by Django 5.2.17 on 2026-08-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_frontendconfiguration_hero_section_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendConfiguration',
        ),
    ]
