# Generated by Django 5.2.17 on 2026-08-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_frontendconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationversion',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='HomeSection',
        ),
        migrations.DeleteModel(
            name='MedicalProcessStep',
        ),
        migrations.DeleteModel(
            name='ModuleRegistry',
        ),
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ['process_type', 'order', 'step_number']},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='faq',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='feature',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='insurancepartner',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_partners', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='managementmember',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='management_members', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='partner',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='process_type',
            field=models.CharField(choices=[('GENERAL', 'General Process'), ('CLAIM', 'Medical Claim'), ('PREAUTH', 'Pre-Authorization'), ('REIMBURSEMENT', 'Reimbursement'), ('NETWORK', 'Network Access'), ('EMERGENCY', 'Emergency')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='processstep',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='providertype',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider_types', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='service',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_ar',
            field=models.CharField(default='تنسيق خدمات التأمين', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(default='Insurance service orchestration', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='cms/hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_cta_ar',
            field=models.CharField(default='تقديم طلب', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_cta_en',
            field=models.CharField(default='Submit a request', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_cta_url',
            field=models.CharField(default='/portal/tickets/create/1/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_cta_ar',
            field=models.CharField(default='استكشف الخدمات', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_cta_en',
            field=models.CharField(default='Explore services', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_cta_url',
            field=models.CharField(default='#services', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ar',
            field=models.TextField(default='قدّم طلبات الخدمة وتابعها وأنجزها بتعاون آمن بين العملاء ومقدمي الخدمة وفرق التأمين.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.TextField(default='Submit, track and resolve service requests with secure collaboration across customers, providers and insurance teams.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ar',
            field=models.CharField(default='مسار واضح لكل طلب تأميني', max_length=220),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(default='One clear path through every insurance request', max_length=220),
        ),
        migrations.AddField(
            model_name='statistic',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.sitesettings'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.sitesettings'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(fields=('site_settings', 'process_type', 'step_number'), name='unique_site_process_step'),
        ),
        migrations.DeleteModel(
            name='ConfigurationVersion',
        ),
    ]
