# Generated by Django 5.2.17 on 2026-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_import_updated_zip_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow_ar',
            field=models.CharField(blank=True, default='تنسيق خدمات التأمين', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, default='Insurance service orchestration', max_length=120, null=True),
        ),
    ]
