# Generated by Django 6.1.1 on 2026-10-01 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizationtype_remove_userprofile_organizations_and_more'),
        ('core', '0012_sitesettings_default_tpa_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='default_tpa_organization',
            new_name='default_processing_organization',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_processing_organization',
            field=models.ForeignKey(blank=True, help_text='Optional default organization for workflow processing.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organization'),
        ),
    ]
