# Generated by Django 5.2.17 on 2026-08-25 07:48

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helpful', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-journal-text', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Knowledge categories',
            },
            bases=(models.Model, apps.core.models.LocalizedModelMixin),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=180)),
                ('title_ar', models.CharField(blank=True, max_length=180)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_ar', models.TextField(blank=True)),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('seo_title_en', models.CharField(blank=True, max_length=160)),
                ('seo_title_ar', models.CharField(blank=True, max_length=160)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', 'title_en'],
            },
            bases=(models.Model, apps.core.models.LocalizedModelMixin),
        ),
    ]
