# Generated by Django 5.2.17 on 2026-08-25 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='tickets.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, to='tickets.product'),
        ),
        migrations.AddField(
            model_name='article',
            name='projects',
            field=models.ManyToManyField(blank=True, to='tickets.project'),
        ),
        migrations.AddField(
            model_name='articlefeedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='knowledge.article'),
        ),
        migrations.AddField(
            model_name='articlefeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='knowledge.knowledgecategory'),
        ),
        migrations.AddConstraint(
            model_name='articlefeedback',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique_user_article_feedback'),
        ),
    ]
