# Generated by Django 5.2.17 on 2026-08-25 07:48

import apps.core.models
import apps.tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('handler', models.CharField(help_text='Allowlisted registry handler key; never raw SQL.', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=140)),
                ('name_ar', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('manage_products', 'Can manage products')],
            },
            bases=(models.Model, apps.core.models.LocalizedModelMixin),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=140)),
                ('name_ar', models.CharField(blank=True, max_length=140)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=15)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tickets.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tickets.product')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'permissions': [('manage_categories', 'Can manage categories')],
            },
            bases=(models.Model, apps.core.models.LocalizedModelMixin),
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_forms', to='tickets.category')),
            ],
            options={
                'permissions': [('manage_forms', 'Can manage dynamic forms'), ('publish_forms', 'Can publish dynamic forms')],
            },
            bases=(models.Model, apps.core.models.LocalizedModelMixin),
        ),
        migrations.CreateModel(
            name='DynamicFormVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('schema', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tickets.dynamicform')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_forms', to='tickets.dynamicformversion'),
        ),
        migrations.CreateModel(
            name='DynamicFieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
                ('label_en', models.CharField(max_length=160)),
                ('label_ar', models.CharField(blank=True, max_length=160)),
                ('control', models.CharField(max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('configuration', models.JSONField(default=dict)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rows', to='tickets.dynamicformversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.product'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=140)),
                ('name_ar', models.CharField(blank=True, max_length=140)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='ticket_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_projects', 'Can manage projects')],
            },
            bases=(models.Model, apps.core.models.LocalizedModelMixin),
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tickets.project'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.project'),
        ),
        migrations.CreateModel(
            name='SavedTicketView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('filters', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=15)),
                ('first_response_minutes', models.PositiveIntegerField(default=240)),
                ('resolution_minutes', models.PositiveIntegerField(default=1440)),
                ('pause_statuses', models.JSONField(blank=True, default=apps.tickets.models.default_pause_statuses)),
                ('business_calendar', models.JSONField(blank=True, default=dict)),
                ('escalation_rules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.category')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.project')),
            ],
            options={
                'permissions': [('manage_sla', 'Can manage SLA policies')],
            },
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_view_all_group_tickets', models.BooleanField(default=True)),
                ('can_edit_group_tickets', models.BooleanField(default=True)),
                ('can_assign_group_tickets', models.BooleanField(default=False)),
                ('can_view_sensitive', models.BooleanField(default=False)),
                ('can_view_internal_notes', models.BooleanField(default=True)),
                ('can_view_restricted_attachments', models.BooleanField(default=False)),
                ('can_access_reports', models.BooleanField(default=False)),
                ('routing_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('auth_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_support_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='support_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tickets.supportgroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.supportgroup'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('subject', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=15)),
                ('visibility', models.CharField(choices=[('standard', 'Standard'), ('restricted', 'Restricted')], default='standard', max_length=20)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=dict)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.category')),
                ('groups', models.ManyToManyField(blank=True, related_name='tickets', to='tickets.supportgroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.slapolicy')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_own', 'Can view own tickets'), ('view_group', 'Can view group tickets'), ('view_all', 'Can view all tickets'), ('assign', 'Can assign tickets'), ('export', 'Can export tickets'), ('view_sensitive', 'Can view sensitive ticket fields'), ('view_internal_notes', 'Can view internal notes')],
            },
        ),
        migrations.CreateModel(
            name='RelatedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='related', max_length=30)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='tickets.ticket')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', validators=[apps.tickets.models.validate_attachment])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField()),
                ('is_restricted', models.BooleanField(default=False)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('mentioned_user_ids', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketDynamicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('values', models.JSONField(default=dict)),
                ('reporting_values', models.JSONField(blank=True, default=dict)),
                ('sensitive_keys', models.JSONField(blank=True, default=list)),
                ('form_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.dynamicformversion')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_data', to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dynamicformversion',
            constraint=models.UniqueConstraint(fields=('form', 'version'), name='unique_dynamic_form_version'),
        ),
        migrations.AddConstraint(
            model_name='dynamicfieldschema',
            constraint=models.UniqueConstraint(fields=('form_version', 'name'), name='unique_version_field'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_project_product'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_product_category'),
        ),
        migrations.AddConstraint(
            model_name='relatedticket',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_related_ticket'),
        ),
    ]
