# Generated by Django 5.2.17 on 2026-08-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_enterprise_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketcomment'),
        ),
    ]
