# Generated by Django 5.2.17 on 2026-08-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketattachment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment_attachment_extensions',
            field=models.CharField(default='pdf,jpg,jpeg,png,doc,docx,xls,xlsx', help_text='Comma-separated allowed file extensions. Example: pdf,jpg,jpeg,png,doc,docx,xls,xlsx', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='comment_attachment_max_count',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of files allowed per comment.'),
        ),
        migrations.AddField(
            model_name='category',
            name='comment_attachment_max_size_mb',
            field=models.PositiveIntegerField(default=5, help_text='Maximum size in MB for each file uploaded with a ticket comment.'),
        ),
    ]
