# Generated by Django 5.2.17 on 2026-08-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_category_comment_attachment_extensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment_attachment_required',
            field=models.BooleanField(default=False, help_text='Enable and require attachments when posting comments for this category.'),
        ),
    ]
