# Generated by Django 5.2.17 on 2026-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_category_comment_attachment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=24, null=True),
        ),
    ]
