# Generated by Django 5.2.17 on 2026-08-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0006_ticketcomment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to make this category available to all authenticated users.', related_name='ticket_categories', to='auth.group'),
        ),
    ]
