# Generated by Django 6.1.1 on 2026-10-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizationtype_remove_userprofile_organizations_and_more'),
        ('tickets', '0008_supportgroup_organizations'),
        ('tpa', '0014_merge_20260930_1202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(default='participant', max_length=40)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_assign', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTaggedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='policy_types',
            field=models.JSONField(blank=True, default=list, help_text='Policy type codes or {code, name} objects.'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_types',
            field=models.ManyToManyField(blank=True, related_name='projects', to='accounts.organizationtype'),
        ),
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='projects', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='reference_format',
            field=models.CharField(default='{prefix}-{year}-{sequence:06d}', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='request_type',
            field=models.CharField(choices=[('service', 'Service Tickets'), ('policy', 'Policies'), ('endorsement', 'Endorsements'), ('claim', 'Claims'), ('task', 'Tasks'), ('other', 'Other')], db_index=True, default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_prefix',
            field=models.CharField(blank=True, help_text='Defaults to project code.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_type',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tpa.policy'),
        ),
        migrations.AddField(
            model_name='ticketapproval',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ticket_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketapproval',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_approvals', to='tickets.approvalstep'),
        ),
        migrations.AddConstraint(
            model_name='ticketapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('step__isnull', True)), fields=('ticket', 'approver'), name='unique_pending_ticket_user_approval'),
        ),
        migrations.AddField(
            model_name='ticketorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_participations', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ticketorganization',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_participants', to='tickets.ticket'),
        ),
        migrations.AddConstraint(
            model_name='ticketsequence',
            constraint=models.UniqueConstraint(fields=('prefix', 'year'), name='unique_ticket_sequence'),
        ),
        migrations.AddField(
            model_name='tickettaggeduser',
            name='tagged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ticket_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettaggeduser',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_participants', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='tickettaggeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_tickets', through='tickets.TicketTaggedUser', through_fields=('ticket', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Organizations whose users may use this support group for ticket routing and reassignment.', related_name='support_groups', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='ticketorganization',
            constraint=models.UniqueConstraint(fields=('ticket', 'organization', 'relationship_type'), name='unique_ticket_organization_role'),
        ),
        migrations.AddConstraint(
            model_name='tickettaggeduser',
            constraint=models.UniqueConstraint(fields=('ticket', 'user'), name='unique_ticket_tag_user'),
        ),
    ]
