# Generated by Django 6.1.1 on 2026-10-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketorganization_ticketsequence_tickettaggeduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creation_attachment_required',
            field=models.BooleanField(default=False, help_text='Require at least one attachment when submitting a new ticket. Named document requirements still apply.', verbose_name='Attachment required during ticket creation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resume_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], help_text='Status to restore when reopening a paused ticket.', max_length=24),
        ),
        migrations.AlterField(
            model_name='category',
            name='comment_attachment_required',
            field=models.BooleanField(default=False, help_text='Require at least one attachment for each comment. Attachments remain optional when disabled.', verbose_name='Attachment required during comments'),
        ),
        migrations.AlterField(
            model_name='category',
            name='reopen_allowed_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Days after closure during which a ticket can be reopened. Set to 0 to disable reopening.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='approval_state',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Additional information required')], db_index=True, default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Additional information required'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
