# Generated by Django 6.1.1 on 2026-10-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_category_creation_attachment_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
