# Generated by Django 5.2.17 on 2026-08-28 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContentPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('eyebrow', models.CharField(blank=True, max_length=200, verbose_name='Eyebrow')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, max_length=500, verbose_name='Button URL')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeCTAPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('eyebrow', models.CharField(blank=True, max_length=200, verbose_name='Eyebrow')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, max_length=500, verbose_name='Button URL')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeFAQPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeFeaturePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon', models.CharField(default='bi-check-circle', max_length=100, verbose_name='Bootstrap icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeHeroPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('eyebrow', models.CharField(blank=True, max_length=200, verbose_name='Eyebrow')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtitle')),
                ('primary_button_text', models.CharField(blank=True, max_length=100, verbose_name='Primary button text')),
                ('primary_button_url', models.CharField(blank=True, max_length=500, verbose_name='Primary button URL')),
                ('secondary_button_text', models.CharField(blank=True, max_length=100, verbose_name='Secondary button text')),
                ('secondary_button_url', models.CharField(blank=True, max_length=500, verbose_name='Secondary button URL')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeImagePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='cms/home/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=250, verbose_name='Alternative text')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('open_new_window', models.BooleanField(default=False, verbose_name='Open in new window')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomePartnerPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='cms/partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeProcessPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='Step number')),
                ('icon', models.CharField(default='bi-check2-circle', max_length=100, verbose_name='Bootstrap icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeSectionHeaderPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('eyebrow', models.CharField(blank=True, max_length=200, verbose_name='Eyebrow')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alignment', models.CharField(choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End')], default='center', max_length=20, verbose_name='Alignment')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeServicePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon', models.CharField(default='bi-shield-check', max_length=100, verbose_name='Bootstrap icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, max_length=500, verbose_name='Button URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeStatisticPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Bootstrap icon')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('suffix', models.CharField(blank=True, max_length=20, verbose_name='Suffix')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HomeTestimonialPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Role')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cms/testimonials/', verbose_name='Photo')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Rating')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
