# Generated by Django 5.2.17 on 2026-08-28 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name English')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name Arabic')),
                ('icon', models.CharField(default='bi-folder', max_length=100, verbose_name='Bootstrap Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Download Category',
                'verbose_name_plural': 'Download Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='DownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=250, verbose_name='Title English')),
                ('title_ar', models.CharField(blank=True, max_length=250, verbose_name='Title Arabic')),
                ('description_en', models.TextField(blank=True, verbose_name='Description English')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description Arabic')),
                ('file', models.FileField(upload_to='downloads/%Y/%m/', verbose_name='File')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cms_plugins.downloadcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Download Document',
                'verbose_name_plural': 'Download Documents',
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
