# Generated by Django 5.2.17 on 2026-08-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
        ('cms_plugins', '0002_downloadcategory_downloaddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWebSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, help_text='Internal name used to identify this CMS section.', max_length=200, verbose_name='Section name')),
                ('html_content', models.TextField(blank=True, help_text='Create content using the visual editor or switch to HTML source mode.', verbose_name='HTML content')),
                ('css_content', models.TextField(blank=True, help_text='Optional CSS for this section.', verbose_name='Custom CSS')),
                ('javascript_content', models.TextField(blank=True, help_text='Optional JavaScript. Trusted administrators only.', verbose_name='Custom JavaScript')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
