# Generated by Django 5.2.17 on 2026-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0003_customwebsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customwebsection',
            name='css_content',
            field=models.TextField(blank=True, verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='customwebsection',
            name='html_content',
            field=models.TextField(blank=True, help_text='Create content using the visual editor or HTML source mode.', verbose_name='HTML content'),
        ),
        migrations.AlterField(
            model_name='customwebsection',
            name='javascript_content',
            field=models.TextField(blank=True, verbose_name='Custom JavaScript'),
        ),
    ]
