# Generated by Django 5.2.17 on 2026-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('request_summary', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('openai_compatible', 'OpenAI-compatible')], default='mock', max_length=30)),
                ('endpoint', models.URLField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('system_prompt', models.TextField(default='Assist with insurance service requests. Never make final coverage or claim decisions.')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('intake_questions', models.JSONField(blank=True, default=list)),
                ('enable_category_suggestion', models.BooleanField(default=True)),
                ('enable_priority_suggestion', models.BooleanField(default=True)),
                ('enable_group_suggestion', models.BooleanField(default=True)),
                ('enable_assignee_suggestion', models.BooleanField(default=False)),
                ('enable_similar_tickets', models.BooleanField(default=True)),
                ('enable_knowledge_suggestion', models.BooleanField(default=True)),
                ('confidence_threshold', models.DecimalField(decimal_places=3, default=0.65, max_digits=4)),
                ('allow_sensitive_fields', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'AI settings',
                'permissions': [('configure_ai', 'Can configure AI')],
            },
        ),
    ]
