# Generated by Django 5.2.17 on 2026-08-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationitem',
            options={'ordering': ['location', 'section', 'order', 'label_en']},
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='cms_navigation_items', to='auth.group'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='emphasized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='icon',
            field=models.CharField(default='bi-circle', help_text='Bootstrap Icons class, for example bi-grid-1x2.', max_length=80),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='cms.page'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='section',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('intelligence', 'Intelligence'), ('resources', 'Resources'), ('administration', 'Administration')], default='workspace', max_length=30),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='cms_pages', to='auth.group'),
        ),
        migrations.AddField(
            model_name='page',
            name='audience',
            field=models.CharField(choices=[('public', 'Public website'), ('portal', 'Authenticated portal'), ('both', 'Public website and portal')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='portal_icon',
            field=models.CharField(default='bi-file-earmark-text', max_length=80),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(blank=True, help_text='Use a local path or external URL. A linked page takes precedence.', max_length=255),
        ),
    ]
