# Generated by Django 5.2.17 on 2026-08-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_navigationitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='route_arguments',
            field=models.JSONField(blank=True, default=list, help_text='Optional positional arguments for the Django route.'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='route_name',
            field=models.CharField(blank=True, help_text='Optional Django route, for example portal:dashboard.', max_length=150),
        ),
    ]
