# Generated by Django 5.2.17 on 2026-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_vanna_local_ollama_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='vannasettings',
            name='chroma_auto_train_successful_queries',
            field=models.BooleanField(default=True, help_text='Store successful governed question/SQL pairs in the domain collection.'),
        ),
        migrations.AddField(
            model_name='vannasettings',
            name='chroma_top_k',
            field=models.PositiveSmallIntegerField(default=8, help_text='Relevant ChromaDB training memories supplied to Ollama per question.'),
        ),
        migrations.AlterField(
            model_name='vannasettings',
            name='provider',
            field=models.CharField(choices=[('demo', 'Safe demo adapter'), ('ollama_vanna', 'Vanna 2.0 + Ollama + ChromaDB (local)'), ('vanna_gateway', 'Vanna 2.0 gateway')], default='demo', max_length=30),
        ),
    ]
