# Generated by Django 5.2.17 on 2026-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_chromadb_retrieval_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysissession',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='queryaudit',
            options={'ordering': ('created_at', 'pk')},
        ),
        migrations.AddField(
            model_name='queryaudit',
            name='response_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
