# Generated by Django 5.2.17 on 2026-08-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=5)),
                ('run_after', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=60)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'run_after', 'created_at'],
                'indexes': [models.Index(fields=['status', 'run_after'], name='job_center__status_73e8df_idx')],
            },
        ),
    ]
